apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Define the Namespace here
namespace: nginx-app

# 2. Point to the base logic and the namespace file
resources:
  - namespace.yaml
  - ../../base