apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-app-config
  namespace: {{ .Release.Namespace }}
data:
  DB_HOST: {{ .Values.db.host | quote }}
  DB_PORT: {{ .Values.db.port | quote }}
  DB_NAME: {{ .Values.db.name | quote }}
  SPRING_JPA_SHOW_SQL: {{ .Values.app.showSql | quote }}
