apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-app-config
  namespace: {{ .Release.Namespace }}
data:
  PAYMENT_DB_URL: {{ .Values.db.url | quote }}
  PAYMENT_API_BASE_URL: app-payment-app-payment-api
