apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.externalDB.internalName }}
spec:
  type: ExternalName
  externalName: {{ .Values.externalDB.host }}
  ports:
  - port: {{ .Values.externalDB.port }}