apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-payment-app
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  secretObjects:                                 
  - secretName: payment-app-secrets             
    type: Opaque
    data: 
    - objectName: db-password                   
      key: db-password                          
    - objectName: db-user
      key: db-user
  parameters:
    usePodIdentity: "false"                     
    useVMManagedIdentity: "true"                 
    userAssignedIdentityID: {{ .Values.azure.clientId | quote }}
    keyvaultName: {{ .Values.azure.keyvaultName | quote }}
    cloudName: ""                                
    objects: |
      array:
        - |
          objectName: payment-app-db-password
          objectType: secret
        - |
          objectName: payment-app-db-user
          objectType: secret
    tenantId: {{ .Values.azure.tenantId | quote }}
